Repository nlesc-nano/data-CAT, pull requests merged in 2020-10, with the labels that each got.

#45 MAINT: Fixed an issue where indices weren't properly passed to the database
  dataCAT/database.py
  tests/test_database.py
Labels: bug

#46 use importlib to check for available modules
  setup.py
Labels: enhancement

#47 Update the pymongo try/except clause
  dataCAT/database.py
Labels: Maintenance

#49 TST: Add tests for windows
  .github/workflows/pythonpackage.yml
  dataCAT/context_managers.py
  tests/test_context_managers.py
  tests/test_database.py
Labels: Tests

#50 Fixed an issue where old `pd.MultiIndex` keys can remain in its `levels` attribute
  dataCAT/database.py
Labels: bug
